-- Seed data for funds table

INSERT INTO funds (fund_name, isin, amc_name, fund_category, fund_type, expense_ratio, min_sip_amount, direct_plan, sector_allocation_json, top_holdings_json, current_nav, nav_as_of) VALUES
-- Large-Cap Funds (8)
('HDFC Top 100 Fund - Direct Plan', 'INF179K01234', 'HDFC', 'Large-Cap', 'Equity', 0.45, 100, true, '{"Finance": 28, "IT": 18, "Consumer": 15, "Energy": 12, "Pharma": 10, "Auto": 8, "Materials": 9}', '[{"symbol": "HDFC Bank", "weight": 8.5}, {"symbol": "ICICI Bank", "weight": 7.2}, {"symbol": "Infosys", "weight": 6.8}, {"symbol": "Reliance", "weight": 5.9}, {"symbol": "ITC", "weight": 4.7}, {"symbol": "TCS", "weight": 4.5}, {"symbol": "Hindustan Unilever", "weight": 4.2}, {"symbol": "Kotak Mahindra Bank", "weight": 3.8}]', 450.25, '2023-12-01'),
('SBI Bluechip Fund - Direct Plan', 'INF200K01235', 'SBI', 'Large-Cap', 'Equity', 0.85, 500, true, '{"Finance": 32, "IT": 20, "Consumer": 14, "Energy": 11, "Pharma": 9, "Auto": 7, "Materials": 7}', '[{"symbol": "HDFC Bank", "weight": 9.1}, {"symbol": "ICICI Bank", "weight": 8.0}, {"symbol": "Infosys", "weight": 7.5}, {"symbol": "Reliance", "weight": 6.2}, {"symbol": "ITC", "weight": 5.0}, {"symbol": "TCS", "weight": 4.8}, {"symbol": "Hindustan Unilever", "weight": 4.5}, {"symbol": "Kotak Mahindra Bank", "weight": 4.0}]', 65.45, '2023-12-01'),
('ICICI Prudential Bluechip Fund - Direct Plan', 'INF109K01236', 'ICICI', 'Large-Cap', 'Equity', 0.75, 100, true, '{"Finance": 30, "IT": 19, "Consumer": 16, "Energy": 13, "Pharma": 8, "Auto": 6, "Materials": 8}', '[{"symbol": "HDFC Bank", "weight": 8.8}, {"symbol": "ICICI Bank", "weight": 7.8}, {"symbol": "Infosys", "weight": 7.0}, {"symbol": "Reliance", "weight": 6.0}, {"symbol": "ITC", "weight": 4.9}, {"symbol": "TCS", "weight": 4.6}, {"symbol": "Hindustan Unilever", "weight": 4.3}, {"symbol": "Kotak Mahindra Bank", "weight": 3.9}]', 78.90, '2023-12-01'),
('Axis Bluechip Fund - Direct Plan', 'INF846K01237', 'Axis', 'Large-Cap', 'Equity', 0.65, 500, true, '{"Finance": 29, "IT": 18, "Consumer": 17, "Energy": 12, "Pharma": 9, "Auto": 7, "Materials": 8}', '[{"symbol": "HDFC Bank", "weight": 8.6}, {"symbol": "ICICI Bank", "weight": 7.5}, {"symbol": "Infosys", "weight": 6.9}, {"symbol": "Reliance", "weight": 5.8}, {"symbol": "ITC", "weight": 4.8}, {"symbol": "TCS", "weight": 4.4}, {"symbol": "Hindustan Unilever", "weight": 4.1}, {"symbol": "Kotak Mahindra Bank", "weight": 3.7}]', 52.30, '2023-12-01'),
('Kotak Bluechip Fund - Direct Plan', 'INF174K01238', 'Kotak', 'Large-Cap', 'Equity', 0.55, 100, true, '{"Finance": 31, "IT": 17, "Consumer": 15, "Energy": 14, "Pharma": 8, "Auto": 8, "Materials": 7}', '[{"symbol": "HDFC Bank", "weight": 9.0}, {"symbol": "ICICI Bank", "weight": 7.9}, {"symbol": "Infosys", "weight": 7.2}, {"symbol": "Reliance", "weight": 6.1}, {"symbol": "ITC", "weight": 5.1}, {"symbol": "TCS", "weight": 4.7}, {"symbol": "Hindustan Unilever", "weight": 4.4}, {"symbol": "Kotak Mahindra Bank", "weight": 4.1}]', 285.75, '2023-12-01'),
('Nippon India Large Cap Fund - Direct Plan', 'INF204K01239', 'Nippon', 'Large-Cap', 'Equity', 0.75, 100, true, '{"Finance": 28, "IT": 20, "Consumer": 14, "Energy": 11, "Pharma": 10, "Auto": 9, "Materials": 8}', '[{"symbol": "HDFC Bank", "weight": 8.3}, {"symbol": "ICICI Bank", "weight": 7.1}, {"symbol": "Infosys", "weight": 6.7}, {"symbol": "Reliance", "weight": 5.7}, {"symbol": "ITC", "weight": 4.6}, {"symbol": "TCS", "weight": 4.3}, {"symbol": "Hindustan Unilever", "weight": 4.0}, {"symbol": "Kotak Mahindra Bank", "weight": 3.6}]', 145.60, '2023-12-01'),
('Mirae Asset Large Cap Fund - Direct Plan', 'INF769K01240', 'Mirae', 'Large-Cap', 'Equity', 0.65, 500, true, '{"Finance": 30, "IT": 19, "Consumer": 16, "Energy": 12, "Pharma": 9, "Auto": 7, "Materials": 7}', '[{"symbol": "HDFC Bank", "weight": 8.7}, {"symbol": "ICICI Bank", "weight": 7.6}, {"symbol": "Infosys", "weight": 7.1}, {"symbol": "Reliance", "weight": 6.0}, {"symbol": "ITC", "weight": 4.9}, {"symbol": "TCS", "weight": 4.5}, {"symbol": "Hindustan Unilever", "weight": 4.2}, {"symbol": "Kotak Mahindra Bank", "weight": 3.8}]', 98.45, '2023-12-01'),
('UTI Nifty 50 Index Fund - Direct Plan', 'INF789F01241', 'UTI', 'Large-Cap', 'Index', 0.15, 100, true, '{"Finance": 33, "IT": 21, "Consumer": 13, "Energy": 10, "Pharma": 8, "Auto": 6, "Materials": 9}', '[{"symbol": "HDFC Bank", "weight": 9.5}, {"symbol": "ICICI Bank", "weight": 8.2}, {"symbol": "Infosys", "weight": 7.8}, {"symbol": "Reliance", "weight": 6.5}, {"symbol": "ITC", "weight": 5.2}, {"symbol": "TCS", "weight": 4.9}, {"symbol": "Hindustan Unilever", "weight": 4.6}, {"symbol": "Kotak Mahindra Bank", "weight": 4.2}]', 225.80, '2023-12-01'),

-- Mid-Cap Funds (8)
('HDFC Mid-Cap Opportunities Fund - Direct Plan', 'INF179K01242', 'HDFC', 'Mid-Cap', 'Equity', 0.85, 100, true, '{"Finance": 15, "IT": 12, "Consumer": 18, "Energy": 16, "Pharma": 14, "Auto": 11, "Materials": 14}', '[{"symbol": "Pidilite Industries", "weight": 4.5}, {"symbol": "SRF", "weight": 4.2}, {"symbol": "Persistent Systems", "weight": 4.0}, {"symbol": "Coromandel International", "weight": 3.8}, {"symbol": "Max Financial", "weight": 3.6}, {"symbol": "Bajaj Auto", "weight": 3.4}, {"symbol": "Dabur India", "weight": 3.2}, {"symbol": "Godrej Consumer", "weight": 3.0}]', 125.90, '2023-12-01'),
('SBI Magnum Midcap Fund - Direct Plan', 'INF200K01243', 'SBI', 'Mid-Cap', 'Equity', 0.95, 500, true, '{"Finance": 14, "IT": 13, "Consumer": 19, "Energy": 15, "Pharma": 13, "Auto": 12, "Materials": 14}', '[{"symbol": "Pidilite Industries", "weight": 4.7}, {"symbol": "SRF", "weight": 4.4}, {"symbol": "Persistent Systems", "weight": 4.2}, {"symbol": "Coromandel International", "weight": 4.0}, {"symbol": "Max Financial", "weight": 3.8}, {"symbol": "Bajaj Auto", "weight": 3.6}, {"symbol": "Dabur India", "weight": 3.4}, {"symbol": "Godrej Consumer", "weight": 3.2}]', 165.75, '2023-12-01'),
('ICICI Prudential Midcap Fund - Direct Plan', 'INF109K01244', 'ICICI', 'Mid-Cap', 'Equity', 0.75, 100, true, '{"Finance": 16, "IT": 11, "Consumer": 20, "Energy": 17, "Pharma": 12, "Auto": 10, "Materials": 14}', '[{"symbol": "Pidilite Industries", "weight": 4.6}, {"symbol": "SRF", "weight": 4.3}, {"symbol": "Persistent Systems", "weight": 4.1}, {"symbol": "Coromandel International", "weight": 3.9}, {"symbol": "Max Financial", "weight": 3.7}, {"symbol": "Bajaj Auto", "weight": 3.5}, {"symbol": "Dabur India", "weight": 3.3}, {"symbol": "Godrej Consumer", "weight": 3.1}]', 185.40, '2023-12-01'),
('Axis Midcap Fund - Direct Plan', 'INF846K01245', 'Axis', 'Mid-Cap', 'Equity', 0.65, 500, true, '{"Finance": 15, "IT": 12, "Consumer": 19, "Energy": 16, "Pharma": 13, "Auto": 11, "Materials": 14}', '[{"symbol": "Pidilite Industries", "weight": 4.4}, {"symbol": "SRF", "weight": 4.1}, {"symbol": "Persistent Systems", "weight": 3.9}, {"symbol": "Coromandel International", "weight": 3.7}, {"symbol": "Max Financial", "weight": 3.5}, {"symbol": "Bajaj Auto", "weight": 3.3}, {"symbol": "Dabur India", "weight": 3.1}, {"symbol": "Godrej Consumer", "weight": 2.9}]', 95.20, '2023-12-01'),
('Kotak Emerging Equity Fund - Direct Plan', 'INF174K01246', 'Kotak', 'Mid-Cap', 'Equity', 0.55, 100, true, '{"Finance": 17, "IT": 10, "Consumer": 18, "Energy": 18, "Pharma": 11, "Auto": 13, "Materials": 13}', '[{"symbol": "Pidilite Industries", "weight": 4.8}, {"symbol": "SRF", "weight": 4.5}, {"symbol": "Persistent Systems", "weight": 4.3}, {"symbol": "Coromandel International", "weight": 4.1}, {"symbol": "Max Financial", "weight": 3.9}, {"symbol": "Bajaj Auto", "weight": 3.7}, {"symbol": "Dabur India", "weight": 3.5}, {"symbol": "Godrej Consumer", "weight": 3.3}]', 75.85, '2023-12-01'),
('Nippon India Growth Fund - Direct Plan', 'INF204K01247', 'Nippon', 'Mid-Cap', 'Equity', 0.75, 100, true, '{"Finance": 14, "IT": 14, "Consumer": 17, "Energy": 15, "Pharma": 15, "Auto": 12, "Materials": 13}', '[{"symbol": "Pidilite Industries", "weight": 4.3}, {"symbol": "SRF", "weight": 4.0}, {"symbol": "Persistent Systems", "weight": 3.8}, {"symbol": "Coromandel International", "weight": 3.6}, {"symbol": "Max Financial", "weight": 3.4}, {"symbol": "Bajaj Auto", "weight": 3.2}, {"symbol": "Dabur India", "weight": 3.0}, {"symbol": "Godrej Consumer", "weight": 2.8}]', 245.60, '2023-12-01'),
('Mirae Asset Midcap Fund - Direct Plan', 'INF769K01248', 'Mirae', 'Mid-Cap', 'Equity', 0.65, 500, true, '{"Finance": 16, "IT": 13, "Consumer": 19, "Energy": 14, "Pharma": 14, "Auto": 11, "Materials": 13}', '[{"symbol": "Pidilite Industries", "weight": 4.5}, {"symbol": "SRF", "weight": 4.2}, {"symbol": "Persistent Systems", "weight": 4.0}, {"symbol": "Coromandel International", "weight": 3.8}, {"symbol": "Max Financial", "weight": 3.6}, {"symbol": "Bajaj Auto", "weight": 3.4}, {"symbol": "Dabur India", "weight": 3.2}, {"symbol": "Godrej Consumer", "weight": 3.0}]', 135.90, '2023-12-01'),
('Franklin India Prima Fund - Direct Plan', 'INF090I01249', 'Franklin', 'Mid-Cap', 'Equity', 0.85, 5000, true, '{"Finance": 13, "IT": 15, "Consumer": 16, "Energy": 17, "Pharma": 12, "Auto": 14, "Materials": 13}', '[{"symbol": "Pidilite Industries", "weight": 4.6}, {"symbol": "SRF", "weight": 4.3}, {"symbol": "Persistent Systems", "weight": 4.1}, {"symbol": "Coromandel International", "weight": 3.9}, {"symbol": "Max Financial", "weight": 3.7}, {"symbol": "Bajaj Auto", "weight": 3.5}, {"symbol": "Dabur India", "weight": 3.3}, {"symbol": "Godrej Consumer", "weight": 3.1}]', 175.25, '2023-12-01'),

-- Small-Cap Funds (4)
('Nippon India Small Cap Fund - Direct Plan', 'INF204K01250', 'Nippon', 'Small-Cap', 'Equity', 0.75, 100, true, '{"Finance": 8, "IT": 10, "Consumer": 22, "Energy": 20, "Pharma": 18, "Auto": 12, "Materials": 10}', '[{"symbol": "KPR Mill", "weight": 3.5}, {"symbol": "Blue Star", "weight": 3.2}, {"symbol": "Finolex Cables", "weight": 3.0}, {"symbol": "Praj Industries", "weight": 2.8}, {"symbol": "Kirloskar Brothers", "weight": 2.6}, {"symbol": "IFB Industries", "weight": 2.4}, {"symbol": "Vesuvius India", "weight": 2.2}, {"symbol": "KSB", "weight": 2.0}]', 85.40, '2023-12-01'),
('HDFC Small Cap Fund - Direct Plan', 'INF179K01251', 'HDFC', 'Small-Cap', 'Equity', 0.85, 100, true, '{"Finance": 9, "IT": 9, "Consumer": 23, "Energy": 19, "Pharma": 19, "Auto": 11, "Materials": 10}', '[{"symbol": "KPR Mill", "weight": 3.6}, {"symbol": "Blue Star", "weight": 3.3}, {"symbol": "Finolex Cables", "weight": 3.1}, {"symbol": "Praj Industries", "weight": 2.9}, {"symbol": "Kirloskar Brothers", "weight": 2.7}, {"symbol": "IFB Industries", "weight": 2.5}, {"symbol": "Vesuvius India", "weight": 2.3}, {"symbol": "KSB", "weight": 2.1}]', 65.75, '2023-12-01'),
('SBI Small Cap Fund - Direct Plan', 'INF200K01252', 'SBI', 'Small-Cap', 'Equity', 0.95, 500, true, '{"Finance": 7, "IT": 11, "Consumer": 21, "Energy": 21, "Pharma": 17, "Auto": 13, "Materials": 10}', '[{"symbol": "KPR Mill", "weight": 3.4}, {"symbol": "Blue Star", "weight": 3.1}, {"symbol": "Finolex Cables", "weight": 2.9}, {"symbol": "Praj Industries", "weight": 2.7}, {"symbol": "Kirloskar Brothers", "weight": 2.5}, {"symbol": "IFB Industries", "weight": 2.3}, {"symbol": "Vesuvius India", "weight": 2.1}, {"symbol": "KSB", "weight": 1.9}]', 115.20, '2023-12-01'),
('ICICI Prudential Smallcap Fund - Direct Plan', 'INF109K01253', 'ICICI', 'Small-Cap', 'Equity', 0.75, 100, true, '{"Finance": 10, "IT": 8, "Consumer": 24, "Energy": 18, "Pharma": 20, "Auto": 10, "Materials": 10}', '[{"symbol": "KPR Mill", "weight": 3.7}, {"symbol": "Blue Star", "weight": 3.4}, {"symbol": "Finolex Cables", "weight": 3.2}, {"symbol": "Praj Industries", "weight": 3.0}, {"symbol": "Kirloskar Brothers", "weight": 2.8}, {"symbol": "IFB Industries", "weight": 2.6}, {"symbol": "Vesuvius India", "weight": 2.4}, {"symbol": "KSB", "weight": 2.2}]', 45.85, '2023-12-01'),

-- Flexi-Cap/Multi-Cap Funds (6)
('Parag Parikh Flexi Cap Fund - Direct Plan', 'INF879O01254', 'PPFAS', 'Flexi-Cap', 'Equity', 0.65, 1000, true, '{"Finance": 25, "IT": 15, "Consumer": 20, "Energy": 15, "Pharma": 10, "Auto": 8, "Materials": 7}', '[{"symbol": "HDFC Bank", "weight": 7.5}, {"symbol": "ITC", "weight": 6.0}, {"symbol": "Pidilite Industries", "weight": 5.5}, {"symbol": "SRF", "weight": 5.0}, {"symbol": "Hindustan Unilever", "weight": 4.5}, {"symbol": "Reliance", "weight": 4.0}, {"symbol": "Infosys", "weight": 3.5}, {"symbol": "ICICI Bank", "weight": 3.0}]', 55.90, '2023-12-01'),
('ICICI Prudential Equity & Debt Fund - Direct Plan', 'INF109K01255', 'ICICI', 'Flexi-Cap', 'Hybrid', 0.75, 100, true, '{"Finance": 20, "IT": 12, "Consumer": 18, "Energy": 14, "Pharma": 12, "Auto": 10, "Materials": 9, "Debt": 5}', '[{"symbol": "HDFC Bank", "weight": 6.0}, {"symbol": "ITC", "weight": 5.0}, {"symbol": "Pidilite Industries", "weight": 4.5}, {"symbol": "SRF", "weight": 4.0}, {"symbol": "Hindustan Unilever", "weight": 3.5}, {"symbol": "Reliance", "weight": 3.0}, {"symbol": "Infosys", "weight": 2.5}, {"symbol": "ICICI Bank", "weight": 2.0}]', 195.75, '2023-12-01'),
('HDFC Flexi Cap Fund - Direct Plan', 'INF179K01256', 'HDFC', 'Flexi-Cap', 'Equity', 0.85, 100, true, '{"Finance": 22, "IT": 16, "Consumer": 19, "Energy": 13, "Pharma": 11, "Auto": 9, "Materials": 10}', '[{"symbol": "HDFC Bank", "weight": 7.0}, {"symbol": "ITC", "weight": 5.5}, {"symbol": "Pidilite Industries", "weight": 5.0}, {"symbol": "SRF", "weight": 4.5}, {"symbol": "Hindustan Unilever", "weight": 4.0}, {"symbol": "Reliance", "weight": 3.5}, {"symbol": "Infosys", "weight": 3.0}, {"symbol": "ICICI Bank", "weight": 2.5}]', 1450.60, '2023-12-01'),
('SBI Flexicap Fund - Direct Plan', 'INF200K01257', 'SBI', 'Flexi-Cap', 'Equity', 0.95, 500, true, '{"Finance": 24, "IT": 14, "Consumer": 21, "Energy": 12, "Pharma": 9, "Auto": 11, "Materials": 9}', '[{"symbol": "HDFC Bank", "weight": 7.2}, {"symbol": "ITC", "weight": 5.7}, {"symbol": "Pidilite Industries", "weight": 5.2}, {"symbol": "SRF", "weight": 4.7}, {"symbol": "Hindustan Unilever", "weight": 4.2}, {"symbol": "Reliance", "weight": 3.7}, {"symbol": "Infosys", "weight": 3.2}, {"symbol": "ICICI Bank", "weight": 2.7}]', 125.40, '2023-12-01'),
('Axis Flexi Cap Fund - Direct Plan', 'INF846K01258', 'Axis', 'Flexi-Cap', 'Equity', 0.65, 500, true, '{"Finance": 23, "IT": 17, "Consumer": 18, "Energy": 16, "Pharma": 10, "Auto": 8, "Materials": 8}', '[{"symbol": "HDFC Bank", "weight": 6.8}, {"symbol": "ITC", "weight": 5.3}, {"symbol": "Pidilite Industries", "weight": 4.8}, {"symbol": "SRF", "weight": 4.3}, {"symbol": "Hindustan Unilever", "weight": 3.8}, {"symbol": "Reliance", "weight": 3.3}, {"symbol": "Infosys", "weight": 2.8}, {"symbol": "ICICI Bank", "weight": 2.3}]', 85.90, '2023-12-01'),
('Kotak Flexicap Fund - Direct Plan', 'INF174K01259', 'Kotak', 'Flexi-Cap', 'Equity', 0.55, 100, true, '{"Finance": 26, "IT": 13, "Consumer": 20, "Energy": 14, "Pharma": 8, "Auto": 10, "Materials": 9}', '[{"symbol": "HDFC Bank", "weight": 7.3}, {"symbol": "ITC", "weight": 5.8}, {"symbol": "Pidilite Industries", "weight": 5.3}, {"symbol": "SRF", "weight": 4.8}, {"symbol": "Hindustan Unilever", "weight": 4.3}, {"symbol": "Reliance", "weight": 3.8}, {"symbol": "Infosys", "weight": 3.3}, {"symbol": "ICICI Bank", "weight": 2.8}]', 65.25, '2023-12-01'),

-- Debt/Bond Funds (4)
('ICICI Prudential Corporate Bond Fund - Direct Plan', 'INF109K01260', 'ICICI', 'Debt', 'Bond', 0.35, 100, true, '{"Corporate Bonds": 70, "Government Securities": 20, "Money Market": 10}', '[{"symbol": "Corporate Bond A", "weight": 15.0}, {"symbol": "Corporate Bond B", "weight": 12.0}, {"symbol": "Government Security 1", "weight": 10.0}, {"symbol": "Government Security 2", "weight": 8.0}, {"symbol": "Money Market Fund", "weight": 5.0}]', 25.45, '2023-12-01'),
('HDFC Corporate Bond Fund - Direct Plan', 'INF179K01261', 'HDFC', 'Debt', 'Bond', 0.45, 100, true, '{"Corporate Bonds": 65, "Government Securities": 25, "Money Market": 10}', '[{"symbol": "Corporate Bond A", "weight": 14.0}, {"symbol": "Corporate Bond B", "weight": 11.0}, {"symbol": "Government Security 1", "weight": 9.0}, {"symbol": "Government Security 2", "weight": 7.0}, {"symbol": "Money Market Fund", "weight": 4.0}]', 28.90, '2023-12-01'),
('SBI Corporate Bond Fund - Direct Plan', 'INF200K01262', 'SBI', 'Debt', 'Bond', 0.55, 500, true, '{"Corporate Bonds": 68, "Government Securities": 22, "Money Market": 10}', '[{"symbol": "Corporate Bond A", "weight": 13.5}, {"symbol": "Corporate Bond B", "weight": 10.5}, {"symbol": "Government Security 1", "weight": 8.5}, {"symbol": "Government Security 2", "weight": 6.5}, {"symbol": "Money Market Fund", "weight": 3.5}]', 32.75, '2023-12-01'),
('Kotak Corporate Bond Fund - Direct Plan', 'INF174K01263', 'Kotak', 'Debt', 'Bond', 0.45, 100, true, '{"Corporate Bonds": 72, "Government Securities": 18, "Money Market": 10}', '[{"symbol": "Corporate Bond A", "weight": 16.0}, {"symbol": "Corporate Bond B", "weight": 13.0}, {"symbol": "Government Security 1", "weight": 11.0}, {"symbol": "Government Security 2", "weight": 9.0}, {"symbol": "Money Market Fund", "weight": 6.0}]', 22.60, '2023-12-01');